image: dynamos-federated-training:local
apiToken: ""
networkVerified: false
integrated:
  enabled: false
  image: dynamos-integrated-services:local
  signingKey: ""
  rabbitPassword: ""
  user: sandbox-researcher
organizations:
  - uva
  - vu
  - tudelft