apiVersion: apps/v1
kind: Deployment
metadata:
  name: dsp-connector-vu
  namespace: {{ .Values.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dsp-connector-vu
  template:
    metadata:
      labels:
        app: dsp-connector-vu
      annotations:
        "linkerd.io/inject" : enabled
    spec:
      containers:
      - name: dsp-connector-vu
        image: {{ .Values.dockerArtifactAccount }}/dsp-connector:{{ .Values.branchNameTag }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: DATA_STEWARD_NAME
          value: VU
        - name: CATALOG_SERVICE_URL
          value: {{ .Values.catalogServiceURL.vu | quote }}
        - name: NEGOTIATION_SERVICE_URL
          value: {{ .Values.negotiationServiceURL.vu | quote }}
        - name: TRANSFER_SERVICE_URL
          value: {{ .Values.transferServiceURL.vu | quote }}
        {{- if .Values.didWebScheme }}
        - name: DID_WEB_SCHEME
          value: {{ .Values.didWebScheme | quote }}
        {{- end }}

---

apiVersion: v1
kind: Service
metadata:
  name: dsp-connector-vu
  namespace: {{ .Values.Namespace }}
spec:
  selector:
    app: dsp-connector-vu
  ports:
    - name: http-dsp-connector-api
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dsp-connector-vu-ingress
  namespace: {{ .Values.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/service-upstream: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: dsp-vu.dsp-connector.svc.cluster.local
    http:
      paths:
      - pathType: Prefix
        path: "/api/v1"
        backend:
          service:
            name: dsp-connector-vu
            port:
              number: 8080
