apiVersion: apps/v1
kind: Deployment
metadata:
  name: negotiation-service-surf
  namespace: {{ .Values.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: negotiation-service-surf
  template:
    metadata:
      labels:
        app: negotiation-service-surf
      annotations:
        "linkerd.io/inject" : enabled
    spec:
      containers:
      - name: negotiation-service-surf
        image: {{ .Values.dockerArtifactAccount }}/negotiation-service:{{ .Values.branchNameTag }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: DATA_STEWARD_NAME
          value: SURF
        - name: ETCD_ENDPOINTS
          value: {{ .Values.etcdEndpoints | quote }}

---

apiVersion: v1
kind: Service
metadata:
  name: negotiation-service-surf
  namespace: {{ .Values.Namespace }}
spec:
  selector:
    app: negotiation-service-surf
  ports:
    - name: http-negotiation-service-api
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
